### ISSUE TITLE
cannot find module "ajv"

### ISSUE THREAD

**Issue by stevanlohja** [open-rpc/generator-client#39]
**Describe the bug**

**To Reproduce**
1. `npm -g update @open-rpc/generator-client`
2. `
pen-rpc-generator-client --version
1.0.28
`
3.  
```
open-rpc-generator-client \
  -s https://raw.githubusercontent.com/open-rpc/examples/master/service-descriptions/petstore-openrpc.json \
  PetStore
Error: added 67 packages from 417 contributors and audited 101 packages in 2.583s
found 0 vulnerabilities


> template-client@1.0.0 build /Users/stev/PetStore
> tsc && typedoc --out docs

index.ts(3,17): error TS2307: Cannot find module 'ajv'.

    at exec (/Users/stev/.nodenv/versions/10.15.0/lib/node_modules/@open-rpc/generator-client/src/bootstrapGeneratedPackage.js:10:14)
    at ChildProcess.exithandler (child_process.js:301:5)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:962:16)
    at Socket.stream.socket.on (internal/child_process.js:381:11)
    at Socket.emit (events.js:182:13)
    at Pipe._handle.close (net.js:610:12)
```

**Expected behavior**
I expected it to generator an open-rpc client.

**Comment by shanejonas** [comment]
fixed in #44
