### ISSUE TITLE
README.md is missing from the generated client

### ISSUE THREAD

**Issue by shanejonas** [open-rpc/generator-client#63]
**Describe the bug**
When I generate a new client. The folder containing the client should contain a README 

**To Reproduce**
1. `open-rpc-generator-client -s https://raw.githubusercontent.com/etclabscore/multi-geth/0718d25e92e568f486be17123e9384ce15d8b48c/openrpc.json EthClient`
2. `cd EthClient`
3. See no `README.md`

**Expected behavior**
I should see at least a generic `README.md` for a generated RPC client

**Screenshots**
![image](https://user-images.githubusercontent.com/364566/54373918-4ec41980-463b-11e9-947e-a511de4c5bee.png)

**Comment by stevanlohja** [comment]
Is `index.ts(5,51): error TS2307: Cannot find module '@open-rpc/schema-utils-js'.
` an issue? 
```
open-rpc-generator-client -s https://raw.githubusercontent.com/etclabscore/multi-geth/0718d25e92e568f486be17123e9384ce15d8b48c/openrpc.json EthClient

Error: added 73 packages from 420 contributors and audited 107 packages in 8.582s
found 0 vulnerabilities


> template-client@1.0.0 build /Users/stev/EthClient
> tsc && typedoc --out docs

index.ts(5,51): error TS2307: Cannot find module '@open-rpc/schema-utils-js'.

    at exec (/Users/stev/.nodenv/versions/10.15.0/lib/node_modules/@open-rpc/generator-client/src/bootstrapGeneratedPackage.js:10:14)
    at ChildProcess.exithandler (child_process.js:301:5)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:962:16)
    at Socket.stream.socket.on (internal/child_process.js:381:11)
    at Socket.emit (events.js:182:13)
    at Pipe._handle.close (net.js:610:12)
```
